# 1. NUMPY BASICS

In [60]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 
import numpy as np
# Let's define a one-dimensional array 
my_list=[10,20,50,60,70]
my_list

[10, 20, 50, 60, 70]

In [61]:
# Let's create a numpy array from the list "my_list"
x=np.array(my_list)
x

array([10, 20, 50, 60, 70])

In [62]:
type(x)

numpy.ndarray

In [63]:
# Multi-dimensional (Matrix definition) 
matrix=np.array([[5,8],[9,13]])
print(type(matrix))
print(matrix)

<class 'numpy.ndarray'>
[[ 5  8]
 [ 9 13]]


**MINI CHALLENGE #1:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [64]:
m=np.array([[4,6,8,7],[20,5,6,9]])
m

array([[ 4,  6,  8,  7],
       [20,  5,  6,  9]])

# 2. BUILT-IN METHODS AND FUNCTIONS 

In [65]:
# "rand()" uniform distribution between 0 and 1
x=np.random.rand(2)
x

array([0.78888268, 0.28738571])

In [66]:
# you can create a matrix of random number as well
x=np.random.rand(5,5)
x

array([[0.96392995, 0.56599171, 0.42637815, 0.57148216, 0.65112499],
       [0.63664759, 0.85468345, 0.46545725, 0.44650882, 0.08987229],
       [0.22146258, 0.99699946, 0.87339763, 0.84360616, 0.22787162],
       [0.91821457, 0.58096956, 0.43569847, 0.42827209, 0.40150928],
       [0.07307672, 0.74589485, 0.51285429, 0.22097061, 0.60139704]])

In [67]:
# "randn()" normal distribution between 0 and 1
x=np.random.randn(10)
x

array([-0.55509683,  0.49056626, -0.11350259, -0.72997172, -0.40240473,
       -0.72156913,  0.12669444, -0.68385753, -0.96015848,  0.25232005])

In [68]:
# "randint" is used to generate random integers between upper and lower bounds
x=np.random.randint(1,10)
x

2

In [69]:
# "randint" can be used to generate a certain number of random itegers as follows
x=np.random.randint(1,100,15)
x

array([18, 14, 17, 33, 90, 33, 13,  2, 17, 92, 25, 50, 12, 83, 67])

In [70]:
# np.arange creates an evenly spaced values within a given interval
x=np.arange(1,50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [71]:
# Create an evenly spaced values with a step of 5
x=np.arange(0,50,5)
x

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [72]:
# create a diagonal of ones and zeros everywhere else
x=np.eye(15)
x

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [73]:
# Array of ones
x=np.zeros(50)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [74]:
# Matrices of ones
x=np.ones((15,15))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.

In [75]:
# Array of zeros


**MINI CHALLENGE #2:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [ ]:
x=int(input("Enter your number"))
a=np.random.randint(0,x,20)
print(a)

# 3. SHAPE, LENGTH, TYPE, RESHAPE, AND MAX/MIN VALUES

In [ ]:
# Let's define a one-dimensional array 
import numpy as np
my_list=[-30,4,50,60,29,15,22,90]
my_list
x=np.array(my_list)
x

In [ ]:
# Get Length of a numpy array
len(x)

In [ ]:
# Get shape
x.shape

In [ ]:
# Obtain the datatype
x.dtype

In [ ]:
# Reshape 1D array into a matrix
z=x.reshape(2,4)
z

In [ ]:
# Obtain the maximum element (value)
x.max()

In [ ]:
# Obtain the minimum element (value)
x.min()

In [ ]:
# Obtain the location of the max element
x.argmax()

In [ ]:
# Obtain the location of the min element
x.argmin()

**MINI CHALLENGE #3:**
- **Write a code that creates a 4x5 array inwhich numbers range between 300 and 500 such that the difference between elements is 10**

In [ ]:
x=np.arange(300,500,10)
z=x.reshape(4,5)
print("Shape: {}".format(z.shape))
print("Matrix:",+z)

**MINI CHALLENGE #4:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [ ]:
x=np.random.randint(-1000,1000,(20,20))
print(x)
print("Shape: {}".format(x.shape))
print("Minimum: ",+x.min())
print("Mean: ",+x.mean())
print("Maximum: ",+x.max())

# 4. MATHEMATICAL OPERATIONS

In [3]:
# np.arange() returns an evenly spaced values within a given interval
import numpy as np
x=np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
y=np.arange(1,10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Add 2 numpy arrays together
sum=x+y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
sqrd=x*x
print(sqrd)

[ 1  4  9 16 25 36 49 64 81]


In [8]:
sqrt=np.sqrt(sqrd)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [10]:
z=np.exp(x)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

**MINI CHALLENGE #5:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```

In [22]:
x=np.array([3,20,30,123])
y=np.array([4,6,7,256])
z=np.sqrt(x**2+y**2)
print("The distance between X and Y is {}".format(z))

The distance between X and Y is [  5.          20.88061302  30.8058436  284.01584463]


# 5. SLICING AND INDEXING 

In [2]:
import numpy as np
x=np.array([20,40,50,21,15])
x

array([20, 40, 50, 21, 15])

In [3]:
# Access specific index from the numpy array
x[0]

20

In [5]:
# Starting from the first index 0 up until and NOT inlcluding the last element
x[0:4]

array([20, 40, 50, 21])

In [6]:
# Broadcasting, altering several values in a numpy array at once
x[0:2]=10
x

array([10, 10, 50, 21, 15])

In [8]:
# Let's define a two dimensional numpy array
y=np.random.randint(1,10,(5,5))
y

array([[7, 9, 4, 9, 4],
       [4, 1, 8, 6, 5],
       [8, 8, 1, 5, 8],
       [3, 9, 8, 5, 2],
       [1, 8, 1, 1, 4]])

In [13]:
# Get a row from a mtrix
y[0]

array([7, 9, 4, 9, 4])

In [14]:
# Get one element
y[2][4]

8

In [15]:
y[:,2]

array([4, 8, 1, 8, 1])

In [16]:
z=y[:3]
z

array([[7, 9, 4, 9, 4],
       [4, 1, 8, 6, 5],
       [8, 8, 1, 5, 8]])

In [18]:
a=y[:,2:]
a

array([[4, 9, 4],
       [8, 6, 5],
       [1, 5, 8],
       [8, 5, 2],
       [1, 1, 4]])

In [19]:
z=y[:,:2]
z

array([[7, 9],
       [4, 1],
       [8, 8],
       [3, 9],
       [1, 8]])

**MINI CHALLENGE #6:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [53]:
x=np.array([[2, 30, 20 ,-2 ,-4],
            [3 ,4 , 40 ,-3 ,-2],
            [-3 ,4 , -6, 90 ,10],
            [25,45 ,34 ,22 ,12],
            [1 ,24, 22 ,32, 37]])
x[4]=-1
print("Replaced Matrix\n\n",+x,"\n\n")
x[0:2,3:5]=x[0:2,3:5]*2
print("Multiple 2x2 Matrix \n\n",+x)

Replaced Matrix

 [[ 2 30 20 -2 -4]
 [ 3  4 40 -3 -2]
 [-3  4 -6 90 10]
 [25 45 34 22 12]
 [-1 -1 -1 -1 -1]] 


Multiple 2x2 Matrix 

 [[ 2 30 20 -4 -8]
 [ 3  4 40 -6 -4]
 [-3  4 -6 90 10]
 [25 45 34 22 12]
 [-1 -1 -1 -1 -1]]


# 6. ELEMENTS SELECTION (CONDITIONAL)

**MINI CHALLENGE #7:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

**MINI CHALLENGE #1 SOLUTION:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [ ]:
x = np.array([[[4, 6, 8, 7] , [20, 5, 6, 9]]])
x

**MINI CHALLENGE #2 SOLUTION:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [ ]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 20)
x

**MINI CHALLENGE #3 SOLUTION:**
- **Write a code that creates a 4x5 array inwhich numbers ranging between 300 and 500 such that the difference between elements is 10**

In [ ]:
x = np.arange(300, 500, 10)
x.shape

In [ ]:
x = x.reshape(4, 5)
print(x)

**MINI CHALLENGE #4 SOLUTION:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [ ]:
x = np.random.randint(-1000, 1000, (20, 20))
print(x)
print('The maximum value is: {} and the minimum value is:{}'.format(x.min(), x.max()))

**MINI CHALLENGE #5 SOLUTION:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```




In [ ]:
X = np.array([3, 20, 30])
Y = np.array([4, 6, 7])
Z = np.sqrt(X**2 + Y**2)
Z

**MINI CHALLENGE #6 SOLUTION:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [ ]:
X[4] = 0
X

In [ ]:
X[:2, 3:]  = X[:2, 3:] * 2

In [ ]:
X

**MINI CHALLENGE #7 SOLUTION:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X%2==1] = 25
X[X<0] = 0
X